# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16iLc5oPooU6aOvF1mzvwHotLCDk7WLY0
"""

# app.py

# --- IMPORTS ---
import streamlit as st
import pandas as pd
import folium
from streamlit_folium import folium_static
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier

# --- PAGE CONFIG MUST BE FIRST ---
st.set_page_config(layout="wide", page_title="Disaster Management Dashboard 🌍")

# --- LOADING DATA ---
@st.cache_data
def load_data():
    # Load your merged earthquake data
    df = pd.read_csv('combined_earthquakes.csv')  # <- Your prepared file
    return df

df_combined = load_data()

# --- BUILD MACHINE LEARNING MODEL ---
def build_model(df):
    features = ['magnitude', 'latitude', 'longitude', 'depth']
    X = df[features]
    y = df['risk_level']
    X['depth'] = X['depth'].fillna(0)

    model = RandomForestClassifier(n_estimators=100, random_state=42)
    model.fit(X, y)
    return model

model = build_model(df_combined)

# --- STREAMLIT DASHBOARD STARTS ---

st.title("🌍 Disaster Management & Real-Time Risk Dashboard")

st.markdown("---")

# --- Section 1: Earthquake Magnitude Over Time ---
st.header("📈 Earthquake Magnitude Over Time")

fig, ax = plt.subplots(figsize=(14,6))
sns.scatterplot(data=df_combined, x='date_time', y='magnitude', hue='source', palette='deep', ax=ax)
ax.set_title('Earthquake Magnitude Over Time')
ax.set_xlabel('Date and Time')
ax.set_ylabel('Magnitude')
ax.grid(True)
st.pyplot(fig)

st.markdown("---")

# --- Section 2: Risk Level Pie Chart ---
st.header("🧨 Risk Level Distribution")

fig2, ax2 = plt.subplots()
df_combined['risk_level'].value_counts().plot.pie(
    autopct='%1.1f%%', startangle=140,
    colors=['red', 'orange', 'yellow', 'green'],
    ax=ax2
)
ax2.set_ylabel('')
ax2.set_title('Risk Levels Across Earthquakes')
st.pyplot(fig2)

st.markdown("---")

# --- Section 3: Earthquake Risk Map ---
st.header("🗺 Earthquake Risk Map")

# Create folium map
map_center = [20, 0]  # World Center
earthquake_map = folium.Map(location=map_center, zoom_start=2)

# Color based on risk level
def get_marker_color(risk):
    if risk == 'Very High':
        return 'darkred'
    elif risk == 'High':
        return 'red'
    elif risk == 'Moderate':
        return 'orange'
    else:
        return 'green'

# Add markers
for index, row in df_combined.iterrows():
    folium.Marker(
        location=[row['latitude'], row['longitude']],
        popup=f"Place: {row['place']}<br>Magnitude: {row['magnitude']}<br>Risk: {row['risk_level']}",
        icon=folium.Icon(color=get_marker_color(row['risk_level']))
    ).add_to(earthquake_map)

folium_static(earthquake_map)

st.markdown("---")

# --- Section 4: Predict Risk for New Earthquake ---
st.header("🔮 Predict Risk for New Earthquake")

mag = st.slider('Magnitude', 0.0, 10.0, 5.5)
lat = st.slider('Latitude', -90.0, 90.0, 0.0)
lon = st.slider('Longitude', -180.0, 180.0, 0.0)
depth = st.slider('Depth (km)', 0.0, 700.0, 10.0)

if st.button('Predict Risk Level'):
    new_quake = pd.DataFrame([{
        'magnitude': mag,
        'latitude': lat,
        'longitude': lon,
        'depth': depth
    }])
    prediction = model.predict(new_quake)[0]
    st.success(f"🚨 Predicted Risk Level: {prediction}")

st.markdown("---")

# --- Section 5: Real-Time Alerts Simulation ---
st.header("🚨 Real-Time Earthquake Alerts")

# Example alerts (Static demo — live alerts can be added separately)
st.warning("🔴 High Risk Alert: 6.9 Magnitude - Near Japan Coast")
st.info("🟠 Moderate Risk Alert: 5.8 Magnitude - Alaska Region")

st.markdown("---")

st.caption("✅ Developed by Hari Maheshwari 🚀 | Disaster Management Project 🌍")

